### ISSUE TITLE
HP - "Modify Draft" button in project Dashboard

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#10]
_(this is VERY frustrating for people that think they will just change their question, and end up having to rebuild the entire project!)_

When I create project, at the end of the process I have a button in the dashboard that reads "Modify Draft".
![Screen Shot 2020-06-03 at 15 38 22](https://user-images.githubusercontent.com/762935/83643437-4d6c6d00-a5b0-11ea-8d72-2452127204bd.png)

However when I click it, my project gets  deleted and I have to start again from importing the data, I have to type all my questions for the task presenter, etc. 
This is not "modify", this is "delete and start again".
![Screen Shot 2020-06-03 at 15 39 30](https://user-images.githubusercontent.com/762935/83643560-6ffe8600-a5b0-11ea-90ff-76082eaccf29.png)

**Option 1**
I would like that When I click "modify" I go back to interface that allows me to create the task presenter, and I see my questions/answers there, so I can modify them. 
**Option 2**
if this is not possible, The button should say "Delete Draft".

**Comment by rosymond** [comment]
I could have put this in a different way:
I would like to be able to edit my task presenter from the builder interface.
At the moment, once I have built the project, the only way to modify the task presenter (for instance, modify the text of a question) is via the code.
I would like to be able to do it from the easy interface that I get while building the project.

![editor](https://user-images.githubusercontent.com/762935/83647615-61ff3400-a5b5-11ea-8c5c-f3cab57d6827.jpg)

**Comment by rosymond** [comment]
**For Option 2 (quick fix before evaluating Option 1)**

When the user clicks on "Modify draft" this popup shows:
"This button will delete your Task Presenter design and take you back to Tasks Import (see Step 2 of the "[How it Works](https://lab.citizenscience.ch/en/about)" procedure)

**Comment by ngeorgomanolis** [comment]
Done. Will reopen issue after evaluating Option #1
