### ISSUE TITLE
MP - Wrong number of tasks in "statistics" tab (project dashboard)

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#11]
_(Medium priority - bug to fix)_

I just created a DRAFT project and imported 7 tasks. I can see them in the "browse tasks" screen.

![Screen Shot 2020-06-03 at 15 46 55](https://user-images.githubusercontent.com/762935/83644350-7b05e600-a5b1-11ea-91b8-6626488c5126.png)

However, If I go in the "Statistics" tab of my project, I see zero tasks, I should see 7.

![Screen Shot 2020-06-03 at 15 45 47](https://user-images.githubusercontent.com/762935/83644234-59a4fa00-a5b1-11ea-9827-e5f2502007dc.png)

**Comment by ngeorgomanolis** [comment]
Nothing weird here. All good. Pybossa cache

Closed!
