### ISSUE TITLE
MP - Tasks Redundancy

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#12]
_(this is annoying, however not many people use it this option at the moment)_

When I go to Project dashboard --> Tasks --> Settings -->Tasks Redundancy I am asked to set the redundancy.
However I do not see the current value of the redundancy (which should be the default one, or whatever I already set in the past).

![Screen Shot 2020-06-03 at 15 50 06](https://user-images.githubusercontent.com/762935/83644873-0bdcc180-a5b2-11ea-89bd-378a73c2f2d3.png)

The current value should be shown in a new line, and shown here:
![redun](https://user-images.githubusercontent.com/762935/83646338-cde09d00-a5b3-11ea-8088-530d60c1766a.jpg)

**Comment by rosymond** [comment]
I also note that the default redundancy is set to 30, which is huge! 
Please change the default redundancy to 5

**Comment by ngeorgomanolis** [comment]
Task redundancy:

Pybossa->pybossa.model.task -> n_answers =5 instead of 30
PB -> Current value cannot be used. Default value label added instead.

**Comment by ngeorgomanolis** [comment]
Seems like, in some cases, **n_answers** is not globally assigned. Need to check it further.
