### ISSUE TITLE
HP - "Discover" page

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#14]
_(this I put high priority because the UX here is quite confusing ....)_
 
In the "discover" page, the default view is currently "featured".
This is the same projects featured also in the homepage, so the first impression is that we only have those projects. The user has to click on "Thinking" to see the other projects.

Required changes:
- the default view should be with all existing projects.

**Option 1**
Simply hide the tab choices and show all projects

![discover](https://user-images.githubusercontent.com/762935/83729097-7724a300-a647-11ea-9c33-6b6eff65f35b.jpg)

**Option 2**
Remove "featured" and substitute with "All Projects". "Thinking" would then show exactly the same projects, which is not nice. It would be nice to hide it, but we can leave with it. "Volunteer Sensing" view should be removed.

![discover2](https://user-images.githubusercontent.com/762935/83729977-ba334600-a648-11ea-9947-bf93c259fba3.jpg)

**Comment by ngeorgomanolis** [comment]
https://lab.citizenscience.ch/en/discover
