### ISSUE TITLE
PROJECT SUPPORT (Crowd4SDG - Snake usecase) - Implement dropdown menu

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#18]
_(Priority TBD)_
In the original implementation of the [Snake ID project](https://snakes.citizenscience.ch/en/) the user identification is helped by a dropdown menu that reacts to the letters entered by the user, suggesting families and species.
![Screen Shot 2020-06-11 at 16 08 47](https://user-images.githubusercontent.com/762935/84394995-f133c980-abfd-11ea-838b-980737d2bd74.png)

This implementation (which took some effort at the time in compiling an exhaustive and scientifically irreproachable list) should be reproduced in the new phase of the project, which is now based on[ a new PB project](https://lab.citizenscience.ch/en/project/83).
The list on families and names is available in a json file.
The file should be added to the interface of the PB project to reproduce the same behaviour.
![Screen Shot 2020-06-11 at 16 16 52](https://user-images.githubusercontent.com/762935/84397624-242a8d00-abff-11ea-8af1-ad32d51a0c45.png)

**Comment by ngeorgomanolis** [comment]
**This is not a c3s-lab-client issue**.
