### ISSUE TITLE
HP - Delete projects

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#20]
I am trying to delete one of my project.

**NOTE!
This is a published project. "Deleting" in this case means that the owner can make the project invisible. However, as per "terms and conditions", we have the right to keep a copy of the analysis data on the server. Also, each contributor owns his/her data and may want them later on.**

If I try with the **dashboard interface**, I get the message in the image.
![Screen Shot 2020-06-17 at 08 25 48](https://user-images.githubusercontent.com/762935/84863094-afc77200-b074-11ea-9cd9-d3e0af405541.png)

If I try via the  **Admin interface**, I get this error:
![Screen Shot 2020-06-17 at 08 25 03](https://user-images.githubusercontent.com/762935/84863172-d5ed1200-b074-11ea-8ee4-e1be447fa3c1.png)

**Comment by ngeorgomanolis** [comment]
deleted projects remain 'active' in db

closed!
