### ISSUE TITLE
HP - Browse Task view 

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#21]
I just imported 68 new task in my project (via CSV file upload)

![Screen Shot 2020-06-17 at 08 48 13](https://user-images.githubusercontent.com/762935/84864900-a7246b00-b077-11ea-88a3-140b037d1b29.png)

However, when I go in the "Browse Task" view, where I should see "all the available tasks for this project" I see only 10 tasks. (May be pagination command missing or not visible?)
I would like to see all my tasks, either in one page or (better) with pagination.

![Screen Shot 2020-06-17 at 08 48 51](https://user-images.githubusercontent.com/762935/84865175-1306d380-b078-11ea-931e-b468a2f6954e.png)

**Comment by ngeorgomanolis** [comment]
There isn't pagination. To be implemented

**Comment by ngeorgomanolis** [comment]
undefined text in success notification fixed.

**Comment by ngeorgomanolis** [comment]
Pagination added in Browse tasks.

https://lab.citizenscience.ch/en/project/60/tasks
