### ISSUE TITLE
Support text in multiple languages

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#26]
One of the projects (106) display tweets in multiple languages, but "non-roman" alphabet (Chinese, Hindi, etc) are not shown correctly. It would be nice to support at least the main alphabets.
(check here: https://smallbusiness.chron.com/pages-displaying-strange-letters-27347.html )
PS: we may also consider emoticons

**Comment by ngeorgomanolis** [comment]
Tweets with non-roman characters are shown correctly. is that the case or something else?

![Screen Shot 2020-10-29 at 12 30 27](https://user-images.githubusercontent.com/6097537/97562840-9222f580-19e2-11eb-9935-adaf1250323d.png)
![Screen Shot 2020-10-29 at 12 30 17](https://user-images.githubusercontent.com/6097537/97562843-93542280-19e2-11eb-8440-56af6cf53dc4.png)
![Screen Shot 2020-10-29 at 12 30 05](https://user-images.githubusercontent.com/6097537/97562845-93ecb900-19e2-11eb-96f1-aaa60a847fa0.png)

**Comment by rosymond** [comment]
If this is working now, then we are fine!
