### ISSUE TITLE
New Posts in Forum

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#28]
**(This would be very nice to have soon ...)**

In the Forum, is impossible to know if there have been new post(s) since the last time I visited. At the moment, every time I (user) access the page I see all discussions closed, so I have to open all of them to see if anything happened.

When there is a new post in the forum, I would like:
- to see a sign (red dot) in the main menu, close to Forum link (standard)
- ideally, this red dot would have also the number of new posts
- inside the forum page, the same dot should signal which one of the discussion(s) have new post(s).

![forum-dot](https://user-images.githubusercontent.com/762935/90775111-b8e4f180-e2f8-11ea-91d7-0eeb188d97d3.jpg)
![forum-dot2](https://user-images.githubusercontent.com/762935/90775122-bda9a580-e2f8-11ea-81ec-93002d0c5d64.jpg)

**Comment by ngeorgomanolis** [comment]
implemented here:
https://github.com/CitizenScienceCenter/c3s-lab-client/tree/feature/forum-notification-badge

![Screen Shot 2020-11-16 at 09 07 42](https://user-images.githubusercontent.com/6097537/99227395-75acf880-27eb-11eb-8b9a-b9e3dee17e97.png)
