### ISSUE TITLE
HP - Error when approving projects

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#32]
When I approve a new project as admin, I get the message "error during project publishing".
The project gets published anyway.

<img width="1440" alt="Screen Shot 2020-10-04 at 11 37 34" src="https://user-images.githubusercontent.com/762935/95045522-8180a780-06e2-11eb-9e70-cc109ca3be71.png">

**Comment by ngeorgomanolis** [comment]
hotfix OK
