### ISSUE TITLE
PB Snake project - reproduce original behaviour

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#33]
We committed to reproduce in the project builder the "suggestions/autofill" behaviour of the original snake project.
Original project: 
https://snakes.citizenscience.ch/en/identification/b6e559f1-4956-4972-9de7-da5203838617
PB:
https://lab.citizenscience.ch/en/project/83/task-presenter

The following 3 changes should be implemented in the current PB project, which are not possible via the task presenter:

**1)** the PB autofill doesn’t seem to handle the “common name” of the snake in the same way as the original system (see result in the two images). We would like to reproduce the same behaviour.
original:
![Screen Shot 2020-10-13 at 10 26 26](https://user-images.githubusercontent.com/762935/95845649-ba57f680-0d4a-11eb-990e-e201fe0ec6b1.png)
current:
![Screen Shot 2020-10-13 at 10 31 27](https://user-images.githubusercontent.com/762935/95845663-bf1caa80-0d4a-11eb-8173-2f71fb93b219.png)

**2)** The option to “click to add” when no match is found should be removed (as it creates wrongly tagged data)
![Screen-Shot-2020-10-13-at-11 54 50](https://user-images.githubusercontent.com/762935/95845949-1b7fca00-0d4b-11eb-85ed-ecb90907941a.jpg)

**3)** The display of the list of names is cut at the letter A while in the original version the full list was displayed.
original
![Screen Shot 2020-10-13 at 11 56 49](https://user-images.githubusercontent.com/762935/95846059-42d69700-0d4b-11eb-9b91-1a2f38501b7d.png)
PB
![Screen Shot 2020-10-13 at 11 57 02](https://user-images.githubusercontent.com/762935/95846089-4e29c280-0d4b-11eb-8c34-74f1fab119ff.png)

**Comment by ngeorgomanolis** [comment]
Improved final version
1. cannot be reproduced
2. fixed
3. nothing to fix. scroll.

https://lab-issue33.staging.citizenscience.ch/en/project/83/task-presenter

**Comment by rosymond** [comment]
1. The behaviour is  changed, and now I can't even find "mamba" .... has the search changed? if I type "mamba", this is what I should find (see image) 
![Screen Shot 2020-11-20 at 13 04 42](https://user-images.githubusercontent.com/762935/99798252-fd1ea280-2b30-11eb-8737-2f4ed536fbc5.png)


3. If you scroll, you only the names starting with letter A. The request is to have **the full list displayed, all letters**, when I scroll.

**Comment by andres112** [comment]
Features implemented  and deployed in production

![Screenshot 2020-12-03 205425](https://user-images.githubusercontent.com/32916294/101081009-cb362300-35a9-11eb-8f1a-9b68624e3e11.png)
